before_commands:
    - "composer update --prefer-source"

tools:
    php_code_sniffer:
        filter:
            paths: ["src/*"]
        config:
            standard: PSR2
    php_code_coverage:
        test_command: phpunit -c travis.phpunit.xml
        config_path:  ~
        filter:
            paths: ["src"]
    php_cpd:
        enabled: true
        excluded_dirs:
          - "config"
          - "test"
          - "vendor"
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["src/*", "test/*"]
    php_loc:
        enabled: true
        excluded_dirs:
          - "config"
          - "test"
          - "vendor"
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
        config:
            ruleset: ~
            code_size_rules:
                cyclomatic_complexity:      true
                npath_complexity:           true
                excessive_method_length:    true
                excessive_class_length:     true
                excessive_parameter_list:   true
                excessive_public_count:     true
                too_many_fields:            true
                too_many_methods:           true
                excessive_class_complexity: true
            design_rules:
                exit_expression:          true
                eval_expression:          true
                goto_statement:           true
                number_of_class_children: true
                depth_of_inheritance:     true
                coupling_between_objects: true
            unused_code_rules:
                unused_private_field:    true
                unused_local_variable:   true
                unused_private_method:   true
                unused_formal_parameter: true
            naming_rules:
                short_variable:       true
                long_variable:        true
                short_method:         true
                constructor_conflict: true
                constant_naming:      true
                boolean_method_name:  true
            controversial_rules:
                superglobals:              true
                camel_case_class_name:     true
                camel_case_property_name:  true
                camel_case_method_name:    true
                camel_case_parameter_name: true
                camel_case_variable_name:  true
    php_pdepend:
        enabled: true
        excluded_dirs:
          - "config"
          - "test"
          - "vendor"
    php_analyzer:
        filter:
            paths: ["test/*"]
    php_sim: true
    sensiolabs_security_checker: true
    external_code_coverage:
        timeout: 1800

checks:
    php:
        code_rating: true
        duplication: true