language: php

php:
  - "5.5"
  - "5.4"

before_script:
  - composer update --no-interaction --dev --prefer-source

script:
  - ./vendor/bin/phpunit -c travis.phpunit.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml