language: php

php:
  - "5.5"
  - "5.4"

before_script:
  - composer install --no-interaction --dev --prefer-source

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml