<?php

/** @var \DmFileman\Form\CreateDirectoryForm $form */
$form = $this->createForm;
$form->prepare();

$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-inline');
$form->setAttribute('action', $this->url('filemanager/create', array('dir' => $this->currentDir)));

/** @var \Zend\Form\View\Helper\FormLabel $formLabel */
$formLabel = $this->plugin('formLabel');

echo $this->form()->openTag($form);

/** @var \Zend\Form\Element $directoryName directory name field */
$directoryName = $form->get('directoryName');
$directoryName->setAttributes(array('class' => 'form-control', 'placeholder' => $directoryName->getLabel()));
$directoryName->setOptions(array('label_attributes' => array('class' => 'sr-only col-xs-4')));
echo $this->bootstrapForm()->inlineBlock(
    $form->getValidationClass($directoryName, 'form-group'),
    $this->formLabel($directoryName),
    $this->formInput($directoryName),
    $this->formElementErrors($directoryName)
);

// Security field
$security = $form->get('security');
echo $this->bootstrapForm()->basicHiddenBlock(
    $form->getValidationClass($security, 'form-group'),
    $this->formHidden($security),
    $this->formElementErrors($security)
);

// Submit field
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');
echo $this->formElement($submit);

echo $this->form()->closeTag();
